services:
  - type: web
    name: khata-backend
    env: node
    buildCommand: npm install --legacy-peer-deps
    startCommand: node server/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FIREBASE_WEB_API_KEY
        sync: false
