services:
  - type: web
    name: khata-backend
    env: node
    buildCommand: npm install --legacy-peer-deps
    startCommand: node server/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_n3uCa2lXqIRb@ep-plain-truth-awv6z84e.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        generateValue: true
